CONSTANT(SPACE, 0x20);//[space]
CONSTANT(SCOLON, 0x3B);//;
CONSTANT(COMMA, 0x2C);//,
CONSTANT(EQUALS, 0x3D);//=
CONSTANT(QUOTE, 0x22);//"
CONSTANT(PCT, 0x25); //%

CONSTANT(MAX_ASCII, 0x7F);

CONSTANT(KEY, 1);
CONSTANT(VALUE_START, 2);
CONSTANT(VALUE, 3);
CONSTANT(STRING, 4);
